version: '3.8'

services:
  app:
    build: .
    container_name: mini-llm-app
    ports:
      - "8000:8000"
    environment:
      - PROVIDER=ollama   # or openai
      - MODEL_NAME=llama3.1:8b
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - .:/app
      - ./models.yml:/app/models.yml
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data: